### ISSUE TITLE
Use of outdated brew cask commands by Ansible

### ISSUE THREAD

**Issue by TomBerriot** [TheGrowingPlant/mac-playbook#131]
The actual version of Ansible uses a deprecated command from actual brew commands.

```
TASK [common : Install homebrew cask packages] *********************************************
failed: [127.0.0.1] (item=google-chrome) => changed=false
  ansible_loop_var: item
  item: google-chrome
  msg: 'Error: Calling brew cask install is disabled! Use brew install [--cask] instead.'
```

There is actually a PR on ansible-collections / community.general to fix this issue.

https://github.com/ansible-collections/community.general/pull/1481

Homebrew version has to be downgraded manually while this issue is not fixed.

https://github.com/ansible-collections/community.general/issues/1524#issuecomment-749226927

I ran a manual `brew upgrade` as the script was breakinb due to an outdated version of curl on my environment.

```
failed: [127.0.0.1] (item=filezilla) => changed=false
  ansible_loop_var: item
  item: filezilla
  msg: |-
    Updating Homebrew...
    Warning: curl is outdated!
    To avoid broken installations, as soon as possible please run:
      brew upgrade
    Or, if you're OK with a less reliable fix:
      brew upgrade curl
    Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```

Maybe we will have to upgrade the version of Ansible when the fix will be released ?

**Comment by notFloran** [comment]
I see that, I had the same issues on my personal mbp.

> Maybe we will have to upgrade the version of Ansible when the fix will be released ?

Yes, we will have to update the requirements.txt then `dev upgrade`

**Comment by notFloran** [comment]
It's fixed
