### ISSUE TITLE
Detail packages installed by homebrew during install

### ISSUE THREAD

**Issue by TomBerriot** [TheGrowingPlant/mac-playbook#59]
As it is done for homebrew cask packages, it would be nice to have more info on what's being installed by homebrew to know if it is stuck in the install of a package.

<img width="509" alt="Capture d’écran 2019-12-19 à 08 51 48" src="https://user-images.githubusercontent.com/11588007/71154863-cfecb480-223c-11ea-8c46-b026b328fddd.png">

**Comment by notFloran** [comment]
The `homebrew`module want a list of packages and the `homebrew_cask` want a package name so I use a loop.

i think the `homebrew_cask` module will evolve like `homebrew`.

**Comment by TomBerriot** [comment]
Sure. Imean that homebrew install output itself is not so verbose, so maybe we could let homebrew output appear on the terminal ?

**Comment by notFloran** [comment]
See https://github.com/ansible/ansible/issues/29428

> so maybe we could let homebrew output appear on the terminal ?

we cant, it's not possible with ansible module.

ansible is not intended to be user-friendly, it is designed for infrastructure automation.
