### ISSUE TITLE
Git noprefix and Grumphp git_blacklist compatibility

### ISSUE THREAD

**Issue by nclsHart** [TheGrowingPlant/mac-playbook#86]
There is a compatibility issue between the git option noprefix and the git_blacklist task of Grumphp. 

Example: 

```
No match for regexp /diff --git (a\/.*) (b\/.*)\n/ Upcoming: diff --git REA
  DME.md README.md
```

I see 3 ways to fix this issues: 

1. wontfix: we keep the git option by default and we must override it localy in projects using grumphp.
2. we remove the option noprefix from global git config and add a git `df` alias including it.
3. we just remove the option noprefix from global git config

**Comment by notFloran** [comment]
I hesitate between 1 and 3

**Comment by nclsHart** [comment]
Maybe we should start by answering this question: is this option bringing some value?

**Comment by notFloran** [comment]
I add it after a tweet : https://github.com/TheGrowingPlant/mac-playbook/commit/95be333d89a6dadf8e2e57efa46472cd05c16063 / https://twitter.com/brandur/status/1182066723337293828

I don't think it brings anything in the end

**Comment by nclsHart** [comment]
So 3 seems to be the best option.
